### ISSUE TITLE
UI Messages not working

### ISSUE THREAD

**Issue by FabianMauz** [ipb-halle/CRIMSy#12]
The messages for errors and warnings are not working anymore. 
( de.ipb_halle.lbac.i18n.UIMessage.java )
Trying to log something in this class does not write anything into the log file.

**Comment by sneumann** [comment]
Check the (my) commits around the hardcoded log4j paths. Did I mess something up ? Yours, Steffen

**Comment by FabianMauz** [comment]
I dont think your changes are the reason. Logging in other classes works as intended. I will look at it later.

**Comment by FabianMauz** [comment]
It seems to be influenced by ajax calls. When i did a "normal" action at a command button, the messages were shown correctly. After switching it to an ajax call, the messages are no more visible.

**Comment by FabianMauz** [comment]
The Problems is that sometimes the update attribute in the triggering tag does not include the growl tag, which is responsible for showing the messages.

**Comment by FabianMauz** [comment]
Solved by  [a7bfbf9] . 
Ajax calls now update the growl component.
