### ISSUE TITLE
Revision of SQL scripts

### ISSUE THREAD

**Issue by FabianMauz** [ipb-halle/CRIMSy#26]
The sql scripts should be updated and if possible simplified. 
The user lbac should have only those rights, which are neccessary for the running programm.

**Comment by fbroda** [comment]
Reorganization of database initialization scripts took place in commit 446bc2d455ceb70f3b90874e290919a92e739501.
Further major refactoring took place in connection with issue #6 (Get rid of UUIDs).

**Comment by FabianMauz** [comment]
Solved by [88a4951]
